# -*- coding: utf-8 -*-
"""biomedical data assignment 5 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uds1m2aPJrrY9Re9VOrcg2WyNxapbkXC
"""

!pip install pydicom -f https://download.pytorch.org/whl/cu117/torch_stable.html

import pydicom

from pydicom import dcmread

import pydicom.data

#the following steps were only for testing

#initiaing a path variable for the diacom file

path=r"/"

#initiaing a name variable for the diacom file

file_name="MR000000.dcm"

#read the files by putting into another variable will be used later

file=pydicom.data.data_manager.get_files(path,file_name)[0]

#finally making the ds variable carry the information for the first diacom file

ds=pydicom.dcmread(file)

ds

from matplotlib import pyplot as plt

path = '/MRI-MyHead.zip'
class DicomReader:
  def init(self):
    pass
    # def f1(self):
    #     arr=[]
    #     for i in range(176):
    #         arr.append("MR000")
    #     for j in range(176):
    #         arr[j]=list(arr[j])
    #         if len(str(j))==1:
    #             arr[j].append("00")
    #             arr[j].append(str(j))
    #             arr[j].append(".dcm")
    #         elif len(str(j))==2:
    #             arr[j].append("0")
    #             arr[j].append(str(j))
    #             arr[j].append(".dcm")
    #         elif len(str(j))==3:
    #             arr[j].append(str(j))
    #             arr[j].append(".dcm")
    #     for i in range(176):
    #         arr[i]="".join(arr[i])
    #     return arr
  def generate_file_names(self):
    arr = []
    for i in range(176):
      file_name = f"MR000{str(i).zfill(3)}.dcm"
      arr.append(file_name)
    return arr

# Instantiate the class and generate filenames
x = DicomReader()
file_names = x.generate_file_names()

# Open the zip file
with zipfile.ZipFile(path, 'r') as zip_ref:
    files_in_zip = zip_ref.namelist()

    for i, pass_dicom in enumerate(file_names):
        # Check if the file exists in the zip
        matching_files = [f for f in files_in_zip if pass_dicom in f]

        if matching_files:
            # Read the DICOM file from the zip archive
            with zip_ref.open(matching_files[0]) as file:
                ds = pydicom.dcmread(file)

                # Display the DICOM image
                plt.imshow(ds.pixel_array, cmap='bone')
                plt.show()

                # Print specific DICOM metadata for the first file
                if i == 0:
                    print(ds[0x0010, 0x0010])  # Patient's name
                    print(ds[0x0008, 0x1030])  # Study description
        else:
            print(f"File not found: {pass_dicom}")
# x=d()
# print(x.f1())
# l=x.f1()
# path = '/MRI-MyHead.zip'
# for i in range (176):
#     pass_dicom = l[i]

    # import zipfile
    # import glob
    # with zipfile.ZipFile(path, 'r') as zip_ref:
    #     files_in_zip = zip_ref.namelist()
    #     matching_files = [f for f in files_in_zip if pass_dicom in f]
    # if matching_files:
    #    filename = matching_files[0]
    #    with zip_ref.open(filename) as file:
    #     ds = pydicom.dcmread(file)
    #     plt.imshow(ds.pixel_array, cmap='bone')
    #     plt.show()
    #     if i == 0:
    #         print(ds[0x0010, 0x0010])
    #         print(ds[0x0008, 0x1030])
    #     else:
    #         print(f"File not found: {pass_dicom} in {path}")
    #read the file by putting it in filename

    # filename = pydicom.data.data_manager.get_files(path, pass_dicom)[0]
    # #put the data in ds
    # ds = pydicom.dcmread(filename)
    # #draw every diacom file in the folder by setting them all to bone layer
    # plt.imshow(ds.pixel_array, cmap='bone')
    # plt.show()
    # #checking the first file to print name and study description
    # if i==0:
    #     print(ds[0x0010,0x0010])
    #     print(ds[0x0008,0x1030])